// Generated by npm run db:types from versioned SQL migrations. Do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]
export type Database = {
  public: {
    Tables: {
      boards: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          title: string
          archived_at: string | null
          background: string
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          title: string
          archived_at?: string | null
          background?: string
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          title?: string
          archived_at?: string | null
          background?: string
        }
        Relationships: []
      }
      card_labels: {
        Row: {
          owner_id: string
          board_id: string
          card_id: string
          label_id: string
        }
        Insert: {
          owner_id?: string
          board_id: string
          card_id: string
          label_id: string
        }
        Update: {
          owner_id?: string
          board_id?: string
          card_id?: string
          label_id?: string
        }
        Relationships: []
      }
      cards: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          board_id: string
          column_id: string
          title: string
          description: string
          position: number
          due_date: string | null
          archived_at: string | null
          completed_at: string | null
          priority: string
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id: string
          column_id: string
          title: string
          description?: string
          position: number
          due_date?: string | null
          archived_at?: string | null
          completed_at?: string | null
          priority?: string
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id?: string
          column_id?: string
          title?: string
          description?: string
          position?: number
          due_date?: string | null
          archived_at?: string | null
          completed_at?: string | null
          priority?: string
        }
        Relationships: []
      }
      columns: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          board_id: string
          title: string
          position: number
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id: string
          title: string
          position: number
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id?: string
          title?: string
          position?: number
        }
        Relationships: []
      }
      labels: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          board_id: string
          name: string
          color: string
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id: string
          name: string
          color?: string
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id?: string
          name?: string
          color?: string
        }
        Relationships: []
      }
      scheduled_sessions: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          card_id: string
          starts_at: string
          ends_at: string
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          card_id: string
          starts_at: string
          ends_at: string
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          card_id?: string
          starts_at?: string
          ends_at?: string
        }
        Relationships: []
      }
      user_preferences: {
        Row: {
          id: string
          owner_id: string
          timezone: string
          week_starts_on: number
          calendar_view: string
          created_at: string
          updated_at: string
          version: number
        }
        Insert: {
          id?: string
          owner_id?: string
          timezone?: string
          week_starts_on?: number
          calendar_view?: string
          created_at?: string
          updated_at?: string
          version?: number
        }
        Update: {
          id?: string
          owner_id?: string
          timezone?: string
          week_starts_on?: number
          calendar_view?: string
          created_at?: string
          updated_at?: string
          version?: number
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      create_board: {
        Args: {
          p_title: string | null
        }
        Returns: string
      }
      create_card: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_column_id: string | null
          p_title: string | null
          p_description?: string | null
          p_due_date?: string | null
          p_priority?: string | null
        }
        Returns: string
      }
      create_column: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_title: string | null
        }
        Returns: string
      }
      delete_board: {
        Args: {
          p_board_id: string | null
          p_version: number | null
        }
        Returns: undefined
      }
      delete_card: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_card_id: string | null
        }
        Returns: undefined
      }
      delete_column: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_column_id: string | null
        }
        Returns: undefined
      }
      get_board_snapshot: {
        Args: {
          p_board_id: string | null
        }
        Returns: Json
      }
      move_card: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_card_id: string | null
          p_column_id: string | null
          p_before_id?: string | null
        }
        Returns: undefined
      }
      move_column: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_column_id: string | null
          p_before_id?: string | null
        }
        Returns: undefined
      }
      save_board: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_title: string | null
          p_archived: boolean | null
          p_background?: string | null
        }
        Returns: undefined
      }
      save_card: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_card_id: string | null
          p_title: string | null
          p_description: string | null
          p_due_date: string | null
          p_completed: boolean | null
          p_archived: boolean | null
          p_priority?: string | null
        }
        Returns: undefined
      }
      save_column: {
        Args: {
          p_board_id: string | null
          p_version: number | null
          p_column_id: string | null
          p_title: string | null
        }
        Returns: undefined
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
