// Generated by npm run db:types from versioned SQL migrations. Do not edit.
export type Database = {
  public: {
    Tables: {
      boards: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          title: string
          archived_at: string | null
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          title: string
          archived_at?: string | null
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          title?: string
          archived_at?: string | null
        }
        Relationships: []
      }
      card_labels: {
        Row: {
          owner_id: string
          board_id: string
          card_id: string
          label_id: string
        }
        Insert: {
          owner_id?: string
          board_id: string
          card_id: string
          label_id: string
        }
        Update: {
          owner_id?: string
          board_id?: string
          card_id?: string
          label_id?: string
        }
        Relationships: []
      }
      cards: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          board_id: string
          column_id: string
          title: string
          description: string
          position: number
          due_date: string | null
          archived_at: string | null
          completed_at: string | null
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id: string
          column_id: string
          title: string
          description?: string
          position: number
          due_date?: string | null
          archived_at?: string | null
          completed_at?: string | null
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id?: string
          column_id?: string
          title?: string
          description?: string
          position?: number
          due_date?: string | null
          archived_at?: string | null
          completed_at?: string | null
        }
        Relationships: []
      }
      columns: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          board_id: string
          title: string
          position: number
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id: string
          title: string
          position: number
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id?: string
          title?: string
          position?: number
        }
        Relationships: []
      }
      labels: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          board_id: string
          name: string
          color: string
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id: string
          name: string
          color?: string
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          board_id?: string
          name?: string
          color?: string
        }
        Relationships: []
      }
      scheduled_sessions: {
        Row: {
          id: string
          owner_id: string
          created_at: string
          updated_at: string
          version: number
          card_id: string
          starts_at: string
          ends_at: string
        }
        Insert: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          card_id: string
          starts_at: string
          ends_at: string
        }
        Update: {
          id?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
          version?: number
          card_id?: string
          starts_at?: string
          ends_at?: string
        }
        Relationships: []
      }
      user_preferences: {
        Row: {
          id: string
          owner_id: string
          timezone: string
          week_starts_on: number
          calendar_view: string
          created_at: string
          updated_at: string
          version: number
        }
        Insert: {
          id?: string
          owner_id?: string
          timezone?: string
          week_starts_on?: number
          calendar_view?: string
          created_at?: string
          updated_at?: string
          version?: number
        }
        Update: {
          id?: string
          owner_id?: string
          timezone?: string
          week_starts_on?: number
          calendar_view?: string
          created_at?: string
          updated_at?: string
          version?: number
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
